apiVersion: v1
kind: Service
metadata:
  name: postgres-warehouse
  namespace: delivery-system
spec:
  type: ClusterIP
  selector:
    app: postgres-warehouse
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
