apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: delivery-system
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: kafka
  ports:
    - port: 29092
      targetPort: 29092
      protocol: TCP
      name: kafka
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: controller
