apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  namespace: delivery-system
spec:
  type: ClusterIP
  selector:
    app: warehouse-service
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
